### ISSUE TITLE
占位符不会旋转

### ISSUE THREAD

**Issue by Wenti-D** [SpeedyOrc-C/Honkai-3rd-II-Martian#2]
网页应用中说：「占位符也同样需要根据声调来旋转。」但实际的显示中似乎并未旋转。
![屏幕截图 2023-10-08 132320](https://github.com/SpeedyOrc-C/Honkai-3rd-II-Martian/assets/73067578/23d13627-937f-4059-a86e-61a79123c46f)

另外我根据网页上的字母表尝试做了一个字体，可以移步[这里](https://github.com/Wenti-D/HI3IIMartianFont)查看。

**Comment by SpeedyOrc-C** [comment]
是我写错了，占位符并不需要旋转。
